# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # 拉取原始碼

      - name: set up JDK 1.8 # 設定JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.232+9.1
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle # 執行編譯命令
#        run: cd android && chmod +x gradlew && ./gradlew app:assembleRelease
        run: chmod +x gradlew && ./gradlew build bundleRelease

      - name: Prepare Release
        id: prepare_release
        run: |
          APK_PATH=`find . -name '*.apk' | grep release`
          echo ::set-output name=apk_path::$APK_PATH
          APK_NAME=`basename $APK_PATH`
          echo ::set-output name=apk_name::$APK_NAME

      - name: Print build PATH
        run: |
          echo ${{steps.prepare_release.outputs.apk_name}}
          echo ${{steps.prepare_release.outputs.bundle_path}}/${{steps.prepare_release.outputs.apk_name}}

      - name: Sign app APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore: ${{secrets.signingkey}}
          key_alias: key0
          keystore_password: a123321a
          key_password: a123321a

      - name: Substitute String
        uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-text: ${{steps.prepare_release.outputs.apk_name}}
          .apk:

      - name: Upload File to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          server-dir: ${{ secrets.server_dir }}${{steps.sub.outputs.result}}/
          local-dir: ${{steps.prepare_release.outputs.apk_path}}
